[Mitsuba Render API](https://mitsuba.readthedocs.io/en/latest/src/api_reference.html#mitsuba.render)


what is stack? what is concatenate? what is difference?

tensor access? reshape?

tensor dimension axis

In [2]:
import torch
import numpy as np

In [ ]:

# numpy array vs. torch tensor
# ndim: attribute | dim(): function returns total dimension
# shape: attribute | size(): function returns tuple for numbers of each dimension or each axis


In [26]:
a_np=np.random.rand(4,3)
print(f'''
Numpy array a is {a_np} 
Total dimension of a is {a_np.ndim}
Size (shape for numpy array) of a: {a_np.shape} 
''')


Numpy array a is [[0.09627079 0.44519929 0.21225374]
 [0.12767496 0.5154487  0.05091656]
 [0.19004726 0.60776083 0.21197943]
 [0.77114997 0.27967544 0.99591505]] 
Total dimension of a is 2
Size of a: (4, 3)



In [28]:
# note that axis and dim are same concept in python
# axis is for numpy
# dim for pytorch
a=torch.randn(4,3)
print(f"""Tensor a: {a}
Total dimension of a: {a.dim()}
Size of a: {a.size()}
, where the first element (dim=0) is for row index
and the second element (dim=1) is for column index""")

Tensor a: tensor([[-1.1126, -1.2868, -0.3590],
        [-0.7533, -1.5815, -0.4133],
        [-0.9247, -2.7437,  1.0302],
        [ 1.0995, -0.2149,  0.0487]])
Total dimension of a: 2
Size of a: torch.Size([4, 3])
, where the first element (dim=0) is for row index
and the second element (dim=1) is for column index


In [36]:
# how to access the second row of tenor (2D)
# size (4,3) =>each row three elements, and with 4 rows
# use "," to dinstinguish axis (dimension) 
print(f'''The second row of tensor a: {a[1,:]}
Another way to access second row a: {a[1,...]}     
The last row of tensor a: {a[-1,:]}''')

The second row of tensor a: tensor([-0.7533, -1.5815, -0.4133])
Another way to access second row a: tensor([-0.7533, -1.5815, -0.4133])     
The last row of tensor a: tensor([ 1.0995, -0.2149,  0.0487])


In [43]:
# meshgrid: create meshgrid(網格) with input two tensors then we obtain
# return that corresponds to grid_x and grid_y respectively. If we combine corresponding 
# element then we get coordinate like cartesian product
x=torch.tensor([1,2,3])
y=torch.tensor([4,5,6])
grid_x,grid_y=torch.meshgrid(x,y)

In [53]:
x.shape[0]==x.shape[-1]

True

In [ ]:
# given two  tensors (3,)
# in squeeze from pytorch, the dim means the new position we want to insert to 
# e.g. dim=0 means (3,)=>(2,3), dim=1 means (3,)=>(3,2) then pytorch will do the pairwise work of u

In [55]:
torch.stack([x,y],dim=1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [48]:
torch.stack([grid_x,grid_y],dim=-1)

tensor([[[1, 4],
         [1, 5],
         [1, 6]],

        [[2, 4],
         [2, 5],
         [2, 6]],

        [[3, 4],
         [3, 5],
         [3, 6]]])

In [18]:
torch.cartesian_prod(x, y)

tensor([[1, 1],
        [1, 2],
        [1, 3],
        [2, 1],
        [2, 2],
        [2, 3],
        [3, 1],
        [3, 2],
        [3, 3]])

In [ ]:
# upper gassussain of square of spp_
# find the smallest integer s.t. side^2>= num
side=1
while(side*side<72):
    side+=1
print(side)
# torch arange generate a tensor with range from 0 to side-1
# devided by side to get the proportion 
us=torch.arange(0,side)/side
vs=torch.arange(0,side)/side

9


In [58]:
# two grid tensors (side,side) document the grids for two tensors    
u,v=torch.meshgrid(us,vs)
# turns to (9,9,2)
uv = torch.stack([u,v], dim = 1)


In [60]:
u

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111],
        [0.2222, 0.2222, 0.2222, 0.2222, 0.2222, 0.2222, 0.2222, 0.2222, 0.2222],
        [0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333],
        [0.4444, 0.4444, 0.4444, 0.4444, 0.4444, 0.4444, 0.4444, 0.4444, 0.4444],
        [0.5556, 0.5556, 0.5556, 0.5556, 0.5556, 0.5556, 0.5556, 0.5556, 0.5556],
        [0.6667, 0.6667, 0.6667, 0.6667, 0.6667, 0.6667, 0.6667, 0.6667, 0.6667],
        [0.7778, 0.7778, 0.7778, 0.7778, 0.7778, 0.7778, 0.7778, 0.7778, 0.7778],
        [0.8889, 0.8889, 0.8889, 0.8889, 0.8889, 0.8889, 0.8889, 0.8889, 0.8889]])

In [59]:
uv

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000],
         [0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778,
          0.8889]],

        [[0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111,
          0.1111],
         [0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778,
          0.8889]],

        [[0.2222, 0.2222, 0.2222, 0.2222, 0.2222, 0.2222, 0.2222, 0.2222,
          0.2222],
         [0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778,
          0.8889]],

        [[0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333,
          0.3333],
         [0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778,
          0.8889]],

        [[0.4444, 0.4444, 0.4444, 0.4444, 0.4444, 0.4444, 0.4444, 0.4444,
          0.4444],
         [0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778,
          0.8889]],

        [[0.5556, 0.5556, 0.5556, 0.5556, 0.5556, 0.5556, 0.

In [41]:
u.shape

torch.Size([9, 9])

In [27]:
uv

tensor([[[0.0000, 0.0000],
         [0.0000, 0.1111],
         [0.0000, 0.2222],
         [0.0000, 0.3333],
         [0.0000, 0.4444],
         [0.0000, 0.5556],
         [0.0000, 0.6667],
         [0.0000, 0.7778],
         [0.0000, 0.8889]],

        [[0.1111, 0.0000],
         [0.1111, 0.1111],
         [0.1111, 0.2222],
         [0.1111, 0.3333],
         [0.1111, 0.4444],
         [0.1111, 0.5556],
         [0.1111, 0.6667],
         [0.1111, 0.7778],
         [0.1111, 0.8889]],

        [[0.2222, 0.0000],
         [0.2222, 0.1111],
         [0.2222, 0.2222],
         [0.2222, 0.3333],
         [0.2222, 0.4444],
         [0.2222, 0.5556],
         [0.2222, 0.6667],
         [0.2222, 0.7778],
         [0.2222, 0.8889]],

        [[0.3333, 0.0000],
         [0.3333, 0.1111],
         [0.3333, 0.2222],
         [0.3333, 0.3333],
         [0.3333, 0.4444],
         [0.3333, 0.5556],
         [0.3333, 0.6667],
         [0.3333, 0.7778],
         [0.3333, 0.8889]],

        [[0.4444, 0.

In [31]:
uv.reshape(-1,2)

tensor([[0.0000, 0.0000],
        [0.0000, 0.1111],
        [0.0000, 0.2222],
        [0.0000, 0.3333],
        [0.0000, 0.4444],
        [0.0000, 0.5556],
        [0.0000, 0.6667],
        [0.0000, 0.7778],
        [0.0000, 0.8889],
        [0.1111, 0.0000],
        [0.1111, 0.1111],
        [0.1111, 0.2222],
        [0.1111, 0.3333],
        [0.1111, 0.4444],
        [0.1111, 0.5556],
        [0.1111, 0.6667],
        [0.1111, 0.7778],
        [0.1111, 0.8889],
        [0.2222, 0.0000],
        [0.2222, 0.1111],
        [0.2222, 0.2222],
        [0.2222, 0.3333],
        [0.2222, 0.4444],
        [0.2222, 0.5556],
        [0.2222, 0.6667],
        [0.2222, 0.7778],
        [0.2222, 0.8889],
        [0.3333, 0.0000],
        [0.3333, 0.1111],
        [0.3333, 0.2222],
        [0.3333, 0.3333],
        [0.3333, 0.4444],
        [0.3333, 0.5556],
        [0.3333, 0.6667],
        [0.3333, 0.7778],
        [0.3333, 0.8889],
        [0.4444, 0.0000],
        [0.4444, 0.1111],
        [0.4

In [38]:
uv=uv.reshape(-1,2)[:64,:]

In [ ]:
uv=

tensor([0., 0.])

In [40]:
torch.randperm(uv.shape[0])

tensor([32, 35, 14, 39, 34, 23, 20, 44, 61, 19, 43, 26, 41, 60, 62, 30, 52, 10,
        11, 36,  9, 51, 42, 16,  4, 40, 37, 56, 28,  5, 49, 25,  3,  7,  6, 15,
        46, 48, 63, 27, 59,  0, 45, 53, 18, 58, 12,  1, 22, 13, 57,  8, 17, 21,
        38, 55, 54, 50,  2, 29, 24, 31, 47, 33])

In [46]:
uv

tensor([[0.0000, 0.0000],
        [0.0000, 0.1111],
        [0.0000, 0.2222],
        [0.0000, 0.3333],
        [0.0000, 0.4444],
        [0.0000, 0.5556],
        [0.0000, 0.6667],
        [0.0000, 0.7778],
        [0.0000, 0.8889],
        [0.1111, 0.0000],
        [0.1111, 0.1111],
        [0.1111, 0.2222],
        [0.1111, 0.3333],
        [0.1111, 0.4444],
        [0.1111, 0.5556],
        [0.1111, 0.6667],
        [0.1111, 0.7778],
        [0.1111, 0.8889],
        [0.2222, 0.0000],
        [0.2222, 0.1111],
        [0.2222, 0.2222],
        [0.2222, 0.3333],
        [0.2222, 0.4444],
        [0.2222, 0.5556],
        [0.2222, 0.6667],
        [0.2222, 0.7778],
        [0.2222, 0.8889],
        [0.3333, 0.0000],
        [0.3333, 0.1111],
        [0.3333, 0.2222],
        [0.3333, 0.3333],
        [0.3333, 0.4444],
        [0.3333, 0.5556],
        [0.3333, 0.6667],
        [0.3333, 0.7778],
        [0.3333, 0.8889],
        [0.4444, 0.0000],
        [0.4444, 0.1111],
        [0.4

In [ ]:
!CUDA_VISIBLE_DEVICES=0,1 nohup python main_exorl.py osfb --seed 42 > test_run_full.log 2>&1 &

In [45]:
uv.unsqueeze(dim=0)

tensor([[[0.0000, 0.0000],
         [0.0000, 0.1111],
         [0.0000, 0.2222],
         [0.0000, 0.3333],
         [0.0000, 0.4444],
         [0.0000, 0.5556],
         [0.0000, 0.6667],
         [0.0000, 0.7778],
         [0.0000, 0.8889],
         [0.1111, 0.0000],
         [0.1111, 0.1111],
         [0.1111, 0.2222],
         [0.1111, 0.3333],
         [0.1111, 0.4444],
         [0.1111, 0.5556],
         [0.1111, 0.6667],
         [0.1111, 0.7778],
         [0.1111, 0.8889],
         [0.2222, 0.0000],
         [0.2222, 0.1111],
         [0.2222, 0.2222],
         [0.2222, 0.3333],
         [0.2222, 0.4444],
         [0.2222, 0.5556],
         [0.2222, 0.6667],
         [0.2222, 0.7778],
         [0.2222, 0.8889],
         [0.3333, 0.0000],
         [0.3333, 0.1111],
         [0.3333, 0.2222],
         [0.3333, 0.3333],
         [0.3333, 0.4444],
         [0.3333, 0.5556],
         [0.3333, 0.6667],
         [0.3333, 0.7778],
         [0.3333, 0.8889],
         [0.4444, 0.0000],
 

In [ ]:

def stratified_sampling_2d(n_pixels, spp_):
    #round spp to square number
    side = 1
    while (side*side< spp_):
        side += 1
    us = torch.arange(0, side)/side 
    vs = torch.arange(0, side)/side
    u, v = torch.meshgrid(us, vs)
    uv = torch.stack([u,v], dim = -1)
    # after reshape the tensor shape becomes ((1+side)*(1+side),2)
    # and then we take out tensor where for 0~_spp and the other dimension holds 
    # this is equivalent to uv.reshape(-1,2)[:spp_,:]
    uv = uv.reshape(-1,2)[:spp_,...]
    # vectorized operation for update the shuffled tensors
    uv = uv[torch.randperm(uv.shape[0]), ...]
    uv_all_pixels = uv.unsqueeze(0).repeat(n_pixels, 1,1).reshape(-1,2)
    wavefront_size = n_pixels * spp_
    jitter = torch.rand((wavefront_size, 2))/side
    return uv_all_pixels + jitter 

In [37]:
torch.randperm(uv.shape[0])

tensor([1, 7, 0, 3, 2, 6, 4, 8, 5])